[package]
name = "spriteloading"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.28.0"
rand = "0.8.5"
raylib = "5.0.1"
serde_json = "1.0.120"
strum = { version = "0.26.3", features = ["derive"] }
strum_macros = "0.26.4"
